"""
Account Manager - Main orchestrator for creating/deleting hosting accounts
Like WHM's "Create Account" - does everything in one shot:
  - Linux user
  - Nginx vhost
  - DNS zone
  - Mail domain
  - MySQL user
  - Directory structure
"""
import os
import shlex
import shutil
import subprocess
import secrets
import string
from typing import Dict, Any
from app.services.nginx import NginxService
from app.services.bind9 import DNSService
from app.services.postfix import MailService
from app.services.mysql_service import MySQLService
from app.services.vsftpd import FTPService
from app.config import settings


class AccountManager:

    @staticmethod
    def _create_default_files(username: str, domain: str, public_html: str, home_dir: str):
        """Create all professional default files for a new hosting account"""

        # ── index.html (Welcome Page) ─────────────────────────────────
        with open(f"{public_html}/index.html", "w") as f:
            f.write(f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome to {domain}</title>
  <style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{ font-family: 'Segoe UI', sans-serif; background: #f0f4f8; display: flex; align-items: center; justify-content: center; min-height: 100vh; }}
    .card {{ background: #fff; border-radius: 16px; padding: 50px 40px; text-align: center; max-width: 560px; width: 90%; box-shadow: 0 10px 40px rgba(0,0,0,.1); }}
    .icon {{ width: 72px; height: 72px; background: #e8f4fd; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 24px; }}
    .icon svg {{ width: 36px; height: 36px; fill: #0066cc; }}
    h1 {{ font-size: 1.8rem; color: #1a1a2e; margin-bottom: 12px; }}
    h1 span {{ color: #0066cc; }}
    p {{ color: #666; line-height: 1.7; margin-bottom: 10px; font-size: .95rem; }}
    code {{ background: #f4f4f4; padding: 3px 8px; border-radius: 4px; font-size: .85rem; color: #333; }}
    .badge {{ display: inline-block; background: #e8f4fd; color: #0066cc; border-radius: 20px; padding: 4px 14px; font-size: .8rem; font-weight: 600; margin-top: 20px; }}
    .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; color: #aaa; font-size: .8rem; }}
  </style>
</head>
<body>
  <div class="card">
    <div class="icon">
      <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></svg>
    </div>
    <h1>Welcome to <span>{domain}</span></h1>
    <p>Your hosting account has been successfully created and is ready to use.</p>
    <p>Upload your website files to: <code>/home/{username}/public_html</code></p>
    <span class="badge">Powered by Nofal Panel</span>
    <div class="footer">
      <p>Account: <strong>{username}</strong> &nbsp;|&nbsp; Nofal Panel v1.0</p>
    </div>
  </div>
</body>
</html>""")

        # ── index.php (PHP fallback) ──────────────────────────────────
        with open(f"{public_html}/index.php", "w") as f:
            f.write(f"""<?php
// Default index.php for {domain}
// Remove this file and replace with your application

header('Location: index.html');
exit;
?>""")

        # ── .htaccess (Apache rules) ──────────────────────────────────
        with open(f"{public_html}/.htaccess", "w") as f:
            f.write(f"""# Default .htaccess for {domain}
# Generated by Nofal Panel

Options -Indexes
Options +FollowSymLinks

# PHP settings
php_value upload_max_filesize 128M
php_value post_max_size 128M
php_value memory_limit 256M
php_value max_execution_time 300

# Security headers
<IfModule mod_headers.c>
    Header set X-Frame-Options "SAMEORIGIN"
    Header set X-XSS-Protection "1; mode=block"
    Header set X-Content-Type-Options "nosniff"
    Header set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

# Block access to sensitive files
<FilesMatch "(\\.htaccess|\\.htpasswd|\\.env|\\.git|composer\\.json|composer\\.lock)$">
    Order Allow,Deny
    Deny from all
</FilesMatch>

# Enable GZIP compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css application/javascript application/json
</IfModule>

# Browser caching
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access 1 year"
    ExpiresByType image/jpeg "access 1 year"
    ExpiresByType image/gif "access 1 year"
    ExpiresByType image/png "access 1 year"
    ExpiresByType image/webp "access 1 year"
    ExpiresByType text/css "access 1 month"
    ExpiresByType application/javascript "access 1 month"
</IfModule>

# Redirect www to non-www (uncomment to enable)
# RewriteEngine On
# RewriteCond %{{HTTP_HOST}} ^www\\.(.*)$ [NC]
# RewriteRule ^(.*)$ https://%1/$1 [R=301,L]

# Force HTTPS (uncomment after SSL is installed)
# RewriteEngine On
# RewriteCond %{{HTTPS}} off
# RewriteRule ^(.*)$ https://%{{HTTP_HOST}}%{{REQUEST_URI}} [L,R=301]
""")

        # ── php.ini (user PHP overrides) ──────────────────────────────
        with open(f"{public_html}/.user.ini", "w") as f:
            f.write(f"""; PHP Settings for {domain}
; Managed by Nofal Panel

upload_max_filesize = 128M
post_max_size = 128M
memory_limit = 256M
max_execution_time = 300
max_input_vars = 3000
date.timezone = UTC
display_errors = Off
log_errors = On
error_log = /home/{username}/logs/php_errors.log
""")

        # ── robots.txt ────────────────────────────────────────────────
        with open(f"{public_html}/robots.txt", "w") as f:
            f.write(f"""# robots.txt for {domain}
User-agent: *
Allow: /

# Sitemap (update with your sitemap URL)
# Sitemap: https://{domain}/sitemap.xml
""")

        # ── favicon.ico (1x1 pixel) ───────────────────────────────────
        # Simple empty file as placeholder
        open(f"{public_html}/favicon.ico", "w").close()

        # ── Error pages ───────────────────────────────────────────────
        error_pages = {
            "400": ("400 Bad Request", "The server could not understand your request."),
            "401": ("401 Unauthorized", "Authentication is required to access this page."),
            "403": ("403 Forbidden", "You do not have permission to access this page."),
            "404": ("404 Not Found", "The page you are looking for could not be found."),
            "500": ("500 Internal Server Error", "An unexpected error occurred on the server."),
            "503": ("503 Service Unavailable", "The service is temporarily unavailable. Please try again later."),
        }
        for code, (title, msg) in error_pages.items():
            with open(f"{public_html}/error_docs/{code}.html", "w") as f:
                f.write(f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title} - {domain}</title>
  <style>
    * {{ margin:0; padding:0; box-sizing:border-box; }}
    body {{ font-family:'Segoe UI',sans-serif; background:#f5f5f5; display:flex; align-items:center; justify-content:center; min-height:100vh; }}
    .box {{ background:#fff; border-radius:12px; padding:48px 40px; text-align:center; max-width:480px; width:90%; box-shadow:0 4px 20px rgba(0,0,0,.08); }}
    h1 {{ font-size:5rem; font-weight:800; color:#0066cc; margin-bottom:8px; }}
    h2 {{ font-size:1.3rem; color:#333; margin-bottom:14px; }}
    p {{ color:#777; line-height:1.7; }}
    a {{ display:inline-block; margin-top:24px; background:#0066cc; color:#fff; padding:10px 28px; border-radius:8px; text-decoration:none; font-weight:600; }}
    a:hover {{ background:#004999; }}
  </style>
</head>
<body>
  <div class="box">
    <h1>{code}</h1>
    <h2>{title.split(' ', 1)[1]}</h2>
    <p>{msg}</p>
    <a href="/">Go Home</a>
  </div>
</body>
</html>""")

        # ── .htaccess error page directives ──────────────────────────
        with open(f"{public_html}/.htaccess", "a") as f:
            f.write("""
# Custom Error Pages
ErrorDocument 400 /error_docs/400.html
ErrorDocument 401 /error_docs/401.html
ErrorDocument 403 /error_docs/403.html
ErrorDocument 404 /error_docs/404.html
ErrorDocument 500 /error_docs/500.html
ErrorDocument 503 /error_docs/503.html
""")

        # ── README for the user ───────────────────────────────────────
        with open(f"{home_dir}/README.txt", "w") as f:
            f.write(f"""===================================
  Nofal Panel - Account: {username}
  Domain: {domain}
===================================

DIRECTORY STRUCTURE:
  ~/public_html/        - Your website files go here
  ~/mail/               - Mail storage
  ~/logs/               - Error and access logs
  ~/tmp/                - Temporary files
  ~/backups/            - Backup files
  ~/ssl/                - SSL certificates
  ~/.ssh/               - SSH keys

DEFAULT FILES IN public_html/:
  index.html            - Default welcome page (replace with your site)
  index.php             - PHP redirect (remove when ready)
  .htaccess             - Apache configuration
  .user.ini             - PHP settings override
  robots.txt            - Search engine instructions
  error_docs/           - Custom error pages (400,401,403,404,500,503)

USEFUL INFORMATION:
  FTP Host:     Your server IP
  FTP User:     {username}
  MySQL Host:   localhost
  Panel URL:    http://YOUR_SERVER_IP:2083

Managed by Nofal Panel v1.0
""")


    @staticmethod
    def _run(cmd: str) -> Dict[str, Any]:
        try:
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=60)
            return {"success": result.returncode == 0, "output": result.stdout.strip(), "error": result.stderr.strip()}
        except Exception as e:
            return {"success": False, "error": str(e)}

    @staticmethod
    def _set_unix_password(username: str, password: str) -> Dict[str, Any]:
        """Set Linux password via chpasswd stdin (avoids shell quoting / injection)."""
        if "\n" in username or "\n" in password or ":" in username:
            return {"success": False, "error": "Invalid characters in username or password"}
        chpasswd_bin = shutil.which("chpasswd") or "/usr/sbin/chpasswd"
        try:
            proc = subprocess.run(
                [chpasswd_bin],
                input=f"{username}:{password}\n",
                text=True,
                capture_output=True,
                timeout=60,
            )
            return {
                "success": proc.returncode == 0,
                "output": (proc.stdout or "").strip(),
                "error": (proc.stderr or "").strip(),
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    @staticmethod
    def generate_password(length: int = 16) -> str:
        chars = string.ascii_letters + string.digits + "!@#$%^&*()"
        return ''.join(secrets.choice(chars) for _ in range(length))

    @staticmethod
    def create_account(
        username: str,
        domain: str,
        password: str,
        email: str,
        ip_address: str,
        package: dict = None
    ) -> Dict[str, Any]:
        """
        Full account creation - like WHM 'Create New Account'
        Creates everything needed for a complete hosting account
        """
        results = {
            "success": False,
            "steps": {},
            "account_info": {}
        }

        home_dir = f"{settings.ACCOUNTS_HOME}/{username}"
        public_html = f"{home_dir}/public_html"
        php_version = package.get("php_version", "8.1") if package else "8.1"
        upload_size = package.get("max_upload_size_mb", 128) if package else 128

        try:
            # ─── Step 1: Create Linux System User ───────────────────────────
            r = AccountManager._run(f"id {shlex.quote(username)} 2>/dev/null")
            if r["success"]:
                results["steps"]["linux_user"] = {"status": "exists", "msg": f"User {username} already exists"}
            else:
                r = AccountManager._run(
                    f"useradd -m -s /bin/bash -d {shlex.quote(home_dir)} {shlex.quote(username)}"
                )
                pw = AccountManager._set_unix_password(username, password) if r["success"] else {"success": True}
                linux_ok = r["success"] and pw.get("success", False)
                linux_msg = (
                    (r.get("error") or r.get("output", "")).strip()
                    if not r["success"]
                    else (pw.get("error") or pw.get("output", "") or "ok").strip()
                )
                results["steps"]["linux_user"] = {
                    "status": "ok" if linux_ok else "error",
                    "msg": linux_msg,
                }

            lu = results["steps"].get("linux_user") or {}
            if lu.get("status") == "error":
                results["error"] = lu.get("msg", "Linux user setup failed")
                return results

            # ─── Step 2: Create Directory Structure ──────────────────────────
            dirs = [
                public_html,
                f"{home_dir}/mail",
                f"{home_dir}/logs",
                f"{home_dir}/tmp",
                f"{home_dir}/backups",
                f"{home_dir}/.ssh",
                f"{home_dir}/ssl",
                f"{home_dir}/cgi-bin",
                f"{public_html}/cgi-bin",
                f"{public_html}/error_docs",
            ]
            for d in dirs:
                os.makedirs(d, exist_ok=True)

            AccountManager._run(
                f"chown -R {shlex.quote(username)}:{shlex.quote(username)} {shlex.quote(home_dir)}"
            )
            AccountManager._run(f"chmod 755 {shlex.quote(home_dir)}")
            AccountManager._run(f"chmod 750 {shlex.quote(home_dir + '/.ssh')}")
            AccountManager._run(f"chmod 711 {shlex.quote(public_html + '/cgi-bin')}")

            # Create all default files
            AccountManager._create_default_files(username, domain, public_html, home_dir)

            results["steps"]["directories"] = {"status": "ok", "home": home_dir, "public_html": public_html}

            # ─── Step 3: Nginx Virtual Host ──────────────────────────────────
            nginx_result = NginxService.create_vhost(
                username=username, domain=domain, document_root=public_html,
                php_version=php_version, upload_size=upload_size
            )
            results["steps"]["nginx"] = {
                "status": "ok" if nginx_result["success"] else "error",
                "msg": nginx_result.get("message", nginx_result.get("error", "")),
            }

            # Nginx = الموقع على السيرفر (مثل WHM). بدون vhost نجاح الحساب غير مكتمل.
            if not nginx_result["success"]:
                results["success"] = False
                results["error"] = nginx_result.get("error", "Nginx failed — check permissions on NGINX_SITES_* and php-fpm socket")
                results["account_info"] = {}
                return results

            # ─── Step 4: DNS Zone ─────────────────────────────────────────────
            dns_result = DNSService.create_zone(domain=domain, ip=ip_address)
            results["steps"]["dns"] = {"status": "ok" if dns_result["success"] else "error", "msg": dns_result.get("message", dns_result.get("error", ""))}

            # ─── Step 5: Mail Domain ──────────────────────────────────────────
            mail_result = MailService.setup_domain(domain=domain)
            results["steps"]["mail_domain"] = {"status": "ok" if mail_result["success"] else "error", "msg": mail_result.get("message", "")}

            # ─── Step 6: MySQL User (no database yet - user creates their own) ─
            mysql_pass = AccountManager.generate_password(12)
            mysql_result = MySQLService.create_user(
                db_user=f"{username}_user",
                db_password=mysql_pass,
            )
            results["steps"]["mysql_user"] = {"status": "ok" if mysql_result["success"] else "error", "msg": mysql_result.get("message", "")}

            # ─── Step 7: FTP Account ──────────────────────────────────────────
            ftp_result = FTPService.create_ftp_account(
                username=username,
                password=password,
                home_dir=public_html
            )
            results["steps"]["ftp"] = {"status": "ok" if ftp_result["success"] else "error", "msg": ftp_result.get("message", "")}

            results["success"] = True
            results["account_info"] = {
                "username": username,
                "domain": domain,
                "home_dir": home_dir,
                "public_html": public_html,
                "ip_address": ip_address,
                "ftp_host": ip_address,
                "ftp_user": username,
                "ftp_port": 21,
                "mysql_user": f"{username}_user",
                "mysql_host": "localhost",
                "panel_url": f"http://{ip_address}:2083",
            }

            return results

        except Exception as e:
            results["error"] = str(e)
            return results

    @staticmethod
    def terminate_account(username: str, domain: str) -> Dict[str, Any]:
        """
        Full account termination - like WHM 'Terminate Account'
        Removes all resources for a hosting account
        """
        results = {"steps": {}}
        home_dir = f"{settings.ACCOUNTS_HOME}/{username}"

        # Step 1: Nginx
        nginx_r = NginxService.delete_vhost(domain)
        results["steps"]["nginx"] = nginx_r

        # Step 2: DNS
        dns_r = DNSService.delete_zone(domain)
        results["steps"]["dns"] = dns_r

        # Step 3: FTP
        ftp_r = FTPService.delete_ftp_account(username)
        results["steps"]["ftp"] = ftp_r

        # Step 4: MySQL user
        mysql_r = MySQLService.drop_user(f"{username}_user")
        results["steps"]["mysql_user"] = mysql_r

        # Step 5: Remove Linux user and home dir
        r = AccountManager._run(f"userdel -r {shlex.quote(username)} 2>/dev/null")
        results["steps"]["linux_user"] = {"success": True, "msg": "Linux user removed"}

        results["success"] = True
        return results

    @staticmethod
    def suspend_account(username: str) -> Dict[str, Any]:
        """Suspend a hosting account"""
        r1 = AccountManager._run(f"usermod -L {shlex.quote(username)}")  # Lock Linux user
        r2 = AccountManager._run(f"usermod -s /bin/false {shlex.quote(username)}")  # Disable shell
        return {"success": r1["success"], "message": f"Account {username} suspended"}

    @staticmethod
    def unsuspend_account(username: str) -> Dict[str, Any]:
        """Unsuspend a hosting account"""
        r1 = AccountManager._run(f"usermod -U {shlex.quote(username)}")  # Unlock Linux user
        r2 = AccountManager._run(f"usermod -s /bin/bash {shlex.quote(username)}")  # Re-enable shell
        return {"success": r1["success"], "message": f"Account {username} unsuspended"}

    @staticmethod
    def change_account_password(username: str, new_password: str) -> Dict[str, Any]:
        """Change the main account (cPanel login) password"""
        r = AccountManager._set_unix_password(username, new_password)
        return {"success": r["success"], "message": f"Password changed for {username}"}
