"""
DNS Service - BIND9 Zone Management
Creates, updates, deletes DNS zones and records
"""
import os
import subprocess
from datetime import datetime
from typing import Dict, Any, List
from app.config import settings


ZONE_TEMPLATE = """; Zone file for {domain}
; Generated by Nofal Panel - {date}

$TTL 3600
@   IN  SOA ns1.{domain}. admin.{domain}. (
            {serial}   ; Serial
            3600       ; Refresh
            1800       ; Retry
            604800     ; Expire
            300        ; Minimum TTL
)

; Name Servers
@       IN  NS      ns1.{domain}.
@       IN  NS      ns2.{domain}.

; A Records
@       IN  A       {ip}
www     IN  A       {ip}
ns1     IN  A       {ip}
ns2     IN  A       {ip}
mail    IN  A       {ip}
ftp     IN  A       {ip}

; MX Records
@       IN  MX  10  mail.{domain}.

; SPF Record
@       IN  TXT     "v=spf1 a mx ip4:{ip} ~all"

; DMARC Record
_dmarc  IN  TXT     "v=DMARC1; p=none; rua=mailto:admin@{domain}"
"""

NAMED_CONF_LOCAL_ENTRY = """
zone "{domain}" {{
    type master;
    file "{zones_dir}/{domain}.zone";
    allow-transfer {{ any; }};
}};
"""


class DNSService:

    @staticmethod
    def _run(cmd: str) -> Dict[str, Any]:
        try:
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=30)
            return {"success": result.returncode == 0, "output": result.stdout.strip(), "error": result.stderr.strip()}
        except Exception as e:
            return {"success": False, "error": str(e)}

    @staticmethod
    def get_serial() -> str:
        """Generate zone serial number based on date"""
        return datetime.now().strftime("%Y%m%d%H")

    @staticmethod
    def create_zone(domain: str, ip: str) -> Dict[str, Any]:
        """Create a new DNS zone for a domain"""
        try:
            zones_dir = settings.BIND_ZONES_DIR
            os.makedirs(zones_dir, exist_ok=True)

            # Create zone file
            zone_content = ZONE_TEMPLATE.format(
                domain=domain,
                ip=ip,
                serial=DNSService.get_serial(),
                date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            )

            zone_file = f"{zones_dir}/{domain}.zone"
            with open(zone_file, "w") as f:
                f.write(zone_content)

            # Add to named.conf.local
            named_conf = "/etc/bind/named.conf.local"
            entry = NAMED_CONF_LOCAL_ENTRY.format(domain=domain, zones_dir=zones_dir)

            # Check if zone already exists in config
            if os.path.exists(named_conf):
                with open(named_conf, "r") as f:
                    existing = f.read()
                if f'zone "{domain}"' not in existing:
                    with open(named_conf, "a") as f:
                        f.write(entry)

            # Set permissions
            DNSService._run(f"chown bind:bind {zone_file}")
            DNSService._run(f"chmod 640 {zone_file}")

            # Reload BIND9
            reload_result = DNSService._run("systemctl reload bind9")
            if reload_result["success"]:
                return {"success": True, "message": f"DNS zone created for {domain}", "zone_file": zone_file}
            else:
                return {"success": False, "error": f"Zone file created but BIND reload failed: {reload_result.get('error')}"}

        except Exception as e:
            return {"success": False, "error": str(e)}

    @staticmethod
    def delete_zone(domain: str) -> Dict[str, Any]:
        """Delete a DNS zone"""
        try:
            zone_file = f"{settings.BIND_ZONES_DIR}/{domain}.zone"
            if os.path.exists(zone_file):
                os.remove(zone_file)

            # Remove from named.conf.local
            named_conf = "/etc/bind/named.conf.local"
            if os.path.exists(named_conf):
                with open(named_conf, "r") as f:
                    lines = f.read()
                # Simple removal - find zone block and remove it
                import re
                pattern = r'\nzone "' + re.escape(domain) + r'"[^}]+}\s*;\n'
                new_content = re.sub(pattern, '\n', lines, flags=re.DOTALL)
                with open(named_conf, "w") as f:
                    f.write(new_content)

            DNSService._run("systemctl reload bind9")
            return {"success": True, "message": f"DNS zone deleted for {domain}"}
        except Exception as e:
            return {"success": False, "error": str(e)}

    @staticmethod
    def add_record(domain: str, record_type: str, name: str, value: str, ttl: int = 3600, priority: int = 0) -> Dict[str, Any]:
        """Add a DNS record to a zone file"""
        try:
            zone_file = f"{settings.BIND_ZONES_DIR}/{domain}.zone"
            if not os.path.exists(zone_file):
                return {"success": False, "error": f"Zone file not found for {domain}"}

            with open(zone_file, "r") as f:
                content = f.read()

            # Update serial
            import re
            new_serial = DNSService.get_serial()
            content = re.sub(r'(\d{10})\s*; Serial', f'{new_serial}   ; Serial', content)

            # Build record line
            if record_type == "MX":
                record_line = f"\n{name}\t{ttl}\tIN\t{record_type}\t{priority}\t{value}"
            else:
                record_line = f"\n{name}\t{ttl}\tIN\t{record_type}\t{value}"

            content += record_line

            with open(zone_file, "w") as f:
                f.write(content)

            DNSService._run("systemctl reload bind9")
            return {"success": True, "message": f"DNS record added: {name} {record_type} {value}"}
        except Exception as e:
            return {"success": False, "error": str(e)}

    @staticmethod
    def delete_record(domain: str, record_type: str, name: str, value: str) -> Dict[str, Any]:
        """Remove a specific DNS record from zone file"""
        try:
            zone_file = f"{settings.BIND_ZONES_DIR}/{domain}.zone"
            if not os.path.exists(zone_file):
                return {"success": False, "error": "Zone file not found"}

            with open(zone_file, "r") as f:
                lines = f.readlines()

            # Filter out the matching record
            new_lines = [l for l in lines if not (name in l and record_type in l and value in l)]

            with open(zone_file, "w") as f:
                f.writelines(new_lines)

            DNSService._run("systemctl reload bind9")
            return {"success": True, "message": "DNS record deleted"}
        except Exception as e:
            return {"success": False, "error": str(e)}

    @staticmethod
    def get_zone_records(domain: str) -> List[Dict[str, Any]]:
        """Parse and return DNS records from zone file"""
        try:
            zone_file = f"{settings.BIND_ZONES_DIR}/{domain}.zone"
            if not os.path.exists(zone_file):
                return []

            records = []
            with open(zone_file, "r") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith(";") or line.startswith("$"):
                        continue
                    parts = line.split()
                    if len(parts) >= 4 and "IN" in parts:
                        idx = parts.index("IN")
                        records.append({
                            "name": parts[0],
                            "ttl": parts[idx - 1] if idx > 0 else "3600",
                            "type": parts[idx + 1],
                            "value": " ".join(parts[idx + 2:]),
                        })
            return records
        except:
            return []

    @staticmethod
    def check_zone(domain: str) -> Dict[str, Any]:
        """Validate zone file syntax"""
        zone_file = f"{settings.BIND_ZONES_DIR}/{domain}.zone"
        result = DNSService._run(f"named-checkzone {domain} {zone_file}")
        return {"valid": result["success"], "output": result.get("output", result.get("error", ""))}

    @staticmethod
    def reload() -> Dict[str, Any]:
        return DNSService._run("systemctl reload bind9")
