"""init schema

Revision ID: f34438d06712
Revises: 
Create Date: 2026-04-14 05:34:47.235589
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34438d06712'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disk_quota_mb', sa.Integer(), nullable=True),
    sa.Column('bandwidth_limit_mb', sa.BigInteger(), nullable=True),
    sa.Column('email_limit', sa.Integer(), nullable=True),
    sa.Column('db_limit', sa.Integer(), nullable=True),
    sa.Column('ftp_limit', sa.Integer(), nullable=True),
    sa.Column('subdomain_limit', sa.Integer(), nullable=True),
    sa.Column('addon_domain_limit', sa.Integer(), nullable=True),
    sa.Column('parked_domain_limit', sa.Integer(), nullable=True),
    sa.Column('has_ssh', sa.Boolean(), nullable=True),
    sa.Column('has_cron', sa.Boolean(), nullable=True),
    sa.Column('has_ssl', sa.Boolean(), nullable=True),
    sa.Column('has_softaculous', sa.Boolean(), nullable=True),
    sa.Column('has_backup', sa.Boolean(), nullable=True),
    sa.Column('max_processes', sa.Integer(), nullable=True),
    sa.Column('max_connections', sa.Integer(), nullable=True),
    sa.Column('php_version', sa.String(length=10), nullable=True),
    sa.Column('max_upload_size_mb', sa.Integer(), nullable=True),
    sa.Column('max_execution_time', sa.Integer(), nullable=True),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=True),
    sa.Column('price_yearly', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('suspend_reason', sa.String(length=255), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('disk_quota_mb', sa.Integer(), nullable=True),
    sa.Column('bandwidth_limit_mb', sa.BigInteger(), nullable=True),
    sa.Column('email_limit', sa.Integer(), nullable=True),
    sa.Column('db_limit', sa.Integer(), nullable=True),
    sa.Column('ftp_limit', sa.Integer(), nullable=True),
    sa.Column('subdomain_limit', sa.Integer(), nullable=True),
    sa.Column('addon_domain_limit', sa.Integer(), nullable=True),
    sa.Column('parked_domain_limit', sa.Integer(), nullable=True),
    sa.Column('disk_used_mb', sa.Integer(), nullable=True),
    sa.Column('bandwidth_used_mb', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('primary_domain', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('nameserver1', sa.String(length=100), nullable=True),
    sa.Column('nameserver2', sa.String(length=100), nullable=True),
    sa.Column('server_user', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('cron_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('minute', sa.String(length=20), nullable=True),
    sa.Column('hour', sa.String(length=20), nullable=True),
    sa.Column('day_of_month', sa.String(length=20), nullable=True),
    sa.Column('month', sa.String(length=20), nullable=True),
    sa.Column('day_of_week', sa.String(length=20), nullable=True),
    sa.Column('email_output', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_jobs_id'), 'cron_jobs', ['id'], unique=False)
    op.create_table('db_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=100), nullable=False),
    sa.Column('db_user', sa.String(length=100), nullable=False),
    sa.Column('db_password_hint', sa.String(length=100), nullable=True),
    sa.Column('db_host', sa.String(length=100), nullable=True),
    sa.Column('db_port', sa.Integer(), nullable=True),
    sa.Column('privileges', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_accounts_db_name'), 'db_accounts', ['db_name'], unique=True)
    op.create_index(op.f('ix_db_accounts_id'), 'db_accounts', ['id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('domain_type', sa.String(length=20), nullable=True),
    sa.Column('redirect_to', sa.String(length=255), nullable=True),
    sa.Column('redirect_type', sa.String(length=10), nullable=True),
    sa.Column('document_root', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('nameserver1', sa.String(length=100), nullable=True),
    sa.Column('nameserver2', sa.String(length=100), nullable=True),
    sa.Column('has_ssl', sa.Boolean(), nullable=True),
    sa.Column('ssl_expiry', sa.DateTime(), nullable=True),
    sa.Column('force_https', sa.Boolean(), nullable=True),
    sa.Column('config_file', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_domain_name'), 'domains', ['domain_name'], unique=True)
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('quota_mb', sa.Integer(), nullable=True),
    sa.Column('used_mb', sa.Integer(), nullable=True),
    sa.Column('is_forwarder', sa.Boolean(), nullable=True),
    sa.Column('forward_to', sa.String(length=500), nullable=True),
    sa.Column('has_autoresponder', sa.Boolean(), nullable=True),
    sa.Column('autoresponder_subject', sa.String(length=255), nullable=True),
    sa.Column('autoresponder_body', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_email'), 'email_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_email_accounts_id'), 'email_accounts', ['id'], unique=False)
    op.create_table('ftp_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('home_directory', sa.String(length=500), nullable=False),
    sa.Column('quota_mb', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ftp_accounts_id'), 'ftp_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_ftp_accounts_username'), 'ftp_accounts', ['username'], unique=True)
    op.create_table('ssl_certs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('cert_type', sa.String(length=20), nullable=True),
    sa.Column('cert_path', sa.String(length=500), nullable=True),
    sa.Column('key_path', sa.String(length=500), nullable=True),
    sa.Column('chain_path', sa.String(length=500), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssl_certs_id'), 'ssl_certs', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pref_key', sa.String(length=80), nullable=False),
    sa.Column('pref_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pref_key', name='uq_user_pref_key')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('dns_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dns_records_id'), 'dns_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dns_records_id'), table_name='dns_records')
    op.drop_table('dns_records')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_ssl_certs_id'), table_name='ssl_certs')
    op.drop_table('ssl_certs')
    op.drop_index(op.f('ix_ftp_accounts_username'), table_name='ftp_accounts')
    op.drop_index(op.f('ix_ftp_accounts_id'), table_name='ftp_accounts')
    op.drop_table('ftp_accounts')
    op.drop_index(op.f('ix_email_accounts_id'), table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_email'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_domain_name'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_db_accounts_id'), table_name='db_accounts')
    op.drop_index(op.f('ix_db_accounts_db_name'), table_name='db_accounts')
    op.drop_table('db_accounts')
    op.drop_index(op.f('ix_cron_jobs_id'), table_name='cron_jobs')
    op.drop_table('cron_jobs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    # ### end Alembic commands ###

